[features]
seeds = false
skip-lint = false
[programs.localnet]
coin_game2 = "7m69C1L22UGQs4NBiyDaPvVz6WRiXKTiPTt1im2hr3Fw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/yvonne/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
